# Generated by Django 5.0.6 on 2025-02-19 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdscripcionActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_adscripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Adscripcion Actual',
                'verbose_name_plural': 'Adscripcion Actual',
            },
        ),
        migrations.CreateModel(
            name='ArmaCorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_armaCorta', models.CharField(max_length=80)),
                ('modelo_armaCorta', models.CharField(max_length=80)),
                ('matricula_armaCorta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArmaLarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_armaLarga', models.CharField(max_length=80)),
                ('modelo_armaLarga', models.CharField(max_length=80)),
                ('matricula_armaLarga', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contactoEmergencia', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono_contactoEmergencia', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('parentesco', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fiscalias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fiscalia', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Fiscalia',
                'verbose_name_plural': 'Fiscalias',
            },
        ),
        migrations.CreateModel(
            name='Folios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguro_social', models.CharField(max_length=12)),
                ('curp', models.CharField(max_length=18)),
                ('cuip', models.CharField(max_length=50)),
                ('folio_credencial', models.CharField(max_length=50)),
                ('taza', models.CharField(max_length=50)),
                ('no_oficio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('placas', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('fiscalia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.fiscalias', verbose_name='Fiscalia')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='EstadoFuerza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='fotos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=9, verbose_name='Género')),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('operativo', models.CharField(choices=[('Operativo', 'Operativo'), ('Administrativo', 'Administrativo'), ('Escolta', 'Escolta'), ('Seguridad Institucional', 'Seguridad Institucional')], max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_actual_adscripcion', models.DateField()),
                ('penultima_adscripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('antepenultima_adscripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500)),
                ('archivo_documental', models.FileField(upload_to='archivos_documentales/')),
                ('formacion_c3', models.BooleanField(default=False)),
                ('formacion_inicial', models.BooleanField(default=False)),
                ('cuip', models.BooleanField(default=False)),
                ('competencias_basicas', models.BooleanField(default=False)),
                ('evaluacion_desempeno', models.BooleanField(default=False)),
                ('cup', models.BooleanField(default=False)),
                ('fecha_vigencia_c3', models.DateField()),
                ('Status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('De vacaciones', 'De vacaciones')], max_length=50)),
                ('adscripcion_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.adscripcionactual')),
                ('arma_corta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.armacorta')),
                ('arma_larga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.armalarga')),
                ('contacto_emergencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contactoemergencia')),
                ('fiscalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.fiscalias')),
                ('folios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.folios')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.secciones')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.vehiculos')),
            ],
            options={
                'verbose_name': 'Estados de Fuerza',
                'verbose_name_plural': 'Estados de Fuerza',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambioAdscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('adscripcion_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_anteriores', to='base.adscripcionactual', verbose_name='Adscripción Anterior')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('estado_fuerza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='base.estadofuerza')),
                ('nueva_adscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_nuevas', to='base.adscripcionactual', verbose_name='Nueva Adscripción')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
