# Generated by Django 5.0.6 on 2025-04-03 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia_vehiculo', models.ImageField(upload_to='fotos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('placas', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('año', models.DateField()),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.RemoveField(
            model_name='solicitudcambioadscripcion',
            name='adscripcion_anterior',
        ),
        migrations.RemoveField(
            model_name='solicitudcambioadscripcion',
            name='nueva_adscripcion',
        ),
        migrations.RemoveField(
            model_name='estadofuerza',
            name='adscripcion_actual',
        ),
        migrations.RemoveField(
            model_name='area',
            name='fiscalia',
        ),
        migrations.RemoveField(
            model_name='area',
            name='user',
        ),
        migrations.RemoveField(
            model_name='estadofuerza',
            name='arma_corta',
        ),
        migrations.RemoveField(
            model_name='estadofuerza',
            name='arma_larga',
        ),
        migrations.RemoveField(
            model_name='estadofuerza',
            name='contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='estadofuerza',
            name='fiscalia',
        ),
        migrations.RemoveField(
            model_name='estadofuerza',
            name='folios',
        ),
        migrations.RemoveField(
            model_name='estadofuerza',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='estadofuerza',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='solicitudcambioadscripcion',
            name='estado_fuerza',
        ),
        migrations.RemoveField(
            model_name='solicitudcambioadscripcion',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='solicitudcambioadscripcion',
            name='solicitante',
        ),
        migrations.DeleteModel(
            name='AdscripcionActual',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='ArmaCorta',
        ),
        migrations.DeleteModel(
            name='ArmaLarga',
        ),
        migrations.DeleteModel(
            name='ContactoEmergencia',
        ),
        migrations.DeleteModel(
            name='Fiscalias',
        ),
        migrations.DeleteModel(
            name='Folios',
        ),
        migrations.DeleteModel(
            name='Secciones',
        ),
        migrations.DeleteModel(
            name='Vehiculos',
        ),
        migrations.DeleteModel(
            name='EstadoFuerza',
        ),
        migrations.DeleteModel(
            name='SolicitudCambioAdscripcion',
        ),
    ]
